name: Update sitewide Fandom scripts

on:
  schedule:
    - cron: '12 12 * * SUN'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm install
      - name: Update wiki list
        run: node wikis.js
      - name: Remove old scripts
        run: rm -rf dist
      - name: Update scripts
        run: node main.js
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist
          git commit -m "Updating sitewide JavaScript."
          git push
      - name: Print errors
        run: cat errors.txt
